name: interactive_chart
description: A candlestick chart that supports hand gestures such as pinch-to-zoom and panning.
version: 0.3.2
homepage: https://github.com/h65wang/flutter-interactive-chart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  shared_preferences: ^2.0.12
  http: ^0.13.4
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

flutter:
