name: interactive_chart
description: A candlestick chart that supports hand gestures such as pinch-to-zoom and panning.
version: 0.3.2
homepage: https://github.com/h65wang/flutter-interactive-chart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
