# This is a basic workflow to help you get started with Actions

name: Deploy to Firebase Hosting

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the sp branch
  push:
    branches: [ sp ]
  pull_request:
    branches: [ sp ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Set working directory
    defaults:
      run:
        working-directory: ./example
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1

      # Runs a single command using the runners shell
      - name: Get packages
        run: flutter pub get

      # Runs a set of commands using the runners shell
      - name: Build web application
        run: flutter build web --web-renderer canvaskit --release
        
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/web
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    # Set working directory
    defaults:
      run:
        working-directory: ./example
        
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build/web
      
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPCHART_1F37D }}'
          channelId: live
          projectId: spchart-1f37d
      
